### PR TITLE
Add support for boot2docker

### PR DESCRIPTION
**Pull request by bobthecow**
Basically, allow proxying ports on arbitrary IP addresses, not just 127.0.0.1.

### CODE REVIEW

**Comment by janl** [comment]
@bobthecow how do you feel about maintaining this module?

**Comment by bobthecow** [comment]
@janl Heh. I've got two itches, and I just scratched both of 'em :)

**Comment by janl** [comment]
@bobthecow I take this as a yes, I added you as a committer to this org :) Welcome!

**Comment by janl** [comment]
+1 on the PR.

**Comment by bobthecow** [comment]
Oops. I accidentally reverted #27 with some copypasta. I'll fix and rebase it.

**Comment by bobthecow** [comment]
There. Fixed.

**Pull request merged**
