### PR TITLE
Add semantic release support.

### PR DESCRIPTION
**Pull request by bobthecow**
What do I need to do to get this on Travis and automagically publishable?

/cc @janl

### CODE REVIEW

**Comment by janl** [comment]
@boennemann could you have a look?

**Comment by bobthecow** [comment]
poke ;)

**Comment by boennemann** [comment]
Woops, I'm sorry, that one slipped through. LGTM, even though I need to add tokens to travis after the merge.

**Comment by boennemann** [comment]
https://github.com/hoodiehq/local-tld/commit/f5c508b9f95f42dd4483654a5c744a9ca25a1b03

**Pull request merged**
