### PR TITLE
Are aliases meant to be an array?

### PR DESCRIPTION
**Pull request by hazeledmands**
Allowing for a config to look like this:

``` json
{
  "3000": {
    "name": "mysite",
    "aliases": ["www", "manage", "admin", "status"]
  }
}
```

to proxy to:

``` json
{ "localhost": "127.0.0.1:80",
  "mysite.dev": "127.0.0.1:3000",
  "mysite.192.168.1.144.xip.io": "127.0.0.1:3000",
  ".*www.mysite.dev": "127.0.0.1:3000",
  ".*www.mysite.192.168.1.144.xip.io": "127.0.0.1:3000",
  ".*manage.mysite.dev": "127.0.0.1:3000",
  ".*manage.mysite.192.168.1.144.xip.io": "127.0.0.1:3000",
  ".*admin.mysite.dev": "127.0.0.1:3000",
  ".*admin.mysite.192.168.1.144.xip.io": "127.0.0.1:3000",
  ".*status.mysite.dev": "127.0.0.1:3000",
  ".*status.mysite.192.168.1.144.xip.io": "127.0.0.1:3000" }
```

### CODE REVIEW

**Comment by janl** [comment]
yeah this was a convenience early on, it should really be an array.

Since this is a BC break, we should bump the major version number and do one of these things:
1. fail gracefully on reading old configs.
2. update old configs on the fly.

I’d vote for 2. if you are willing to write the code :)

**Comment by hazeledmands** [comment]
Alternatively, we could support both? Easy fix and probably not a breaking change... :)

**Comment by janl** [comment]
not worth it. Let’s just migrate everyone to the new format and move on.

**Comment by hazeledmands** [comment]
Alright then, pull request on its way.

**Comment by janl** [comment]
grand, thanks! :)

**Comment by hazeledmands** [comment]
@janl There -- how's this?

**Comment by hazeledmands** [comment]
(I hope you don't mind -- I moved all of the config file-related code into its own file. Most of it's unchanged.)

**Comment by janl** [comment]
Looking good!

**Pull request merged**
