### PR TITLE
Replace ipfw with pf.

### LINKED ISSUE #26: Compatibility with Yosemite
Might be interesting to follow what come up here: https://github.com/basecamp/pow/issues/452

ipfw is removed from yosemite, so we might have to backport some of the suff in pow again!

### PR DESCRIPTION
**Pull request by bobthecow**
See basecamp/pow#453

Fixes #26

### CODE REVIEW

**Comment by janl** [comment]
I could only skim 453, what is the story on older Macs? Do we need to worry about backwards compatibility?

**Comment by bobthecow** [comment]
Per the wall of text in basecamp/pow#452, this works in Mavericks as well. This would mean local-tld > 1.4.0 wouldn't work on Mountain Lion, but that seems reasonable?

> Test 0.4.3 installation followed by an upgrade to 0.5.0 on Mavericks. Verify that the ipfw rules are replaced by pf rules, and that uninstalling both versions works without issue. Then test a clean install of 0.5.0 on Mavericks for good measure.

I don't have a copy of Mavericks to test with, but: https://github.com/basecamp/pow/pull/453#issuecomment-58414142

> Works on Mavericks for me.

**Comment by janl** [comment]
LGTM, can we make this merge 2.0.0 and then specify OS requirement > ML?

**Comment by bobthecow** [comment]
Oh, yeah, it should bump to 2.0.0 after merge.

**Comment by bobthecow** [comment]
Oh, just kidding. I looked at the tags list in git, not at the package.json version… this will make release 5.0.0 :)

**Comment by bobthecow** [comment]
f4a8469 should make this work with pre-Mavericks as well.

**Comment by janl** [comment]
heh, I did mean _next major version_ :D

**Comment by bobthecow** [comment]
Is there any particular reason to use (or not use) tagged releases here?

**Comment by bobthecow** [comment]
And any thoughts on the pre-Mavericks fallback? I didn't see any way of making an explicit `>10.9` os version constraint, other than making the install script fail with a message about installing the older version. But this seems like it'll do the trick without introducing too much complexity. Thoughts?

**Comment by janl** [comment]
@bobthecow I was thinking about package.json `os`, but it seems to be only platforms, not versions. no worries, then.

On tags: please use tags :) — We moved all other Hoodie tuff to use https://github.com/boennemann/grunt-semantic-release (write up here: http://blog.hood.ie/2014/09/semantic-releases/) and it wouldn’t hurt to have local-ltd in the fold (cc @boennemann :)

**Comment by bobthecow** [comment]
@boennemann Poke ;)

What needs to be done with this?

**Comment by boennemann** [comment]
@bobthecow Should be set up already https://github.com/hoodiehq/local-tld/commit/f5c508b9f95f42dd4483654a5c744a9ca25a1b03 :)

**Comment by bobthecow** [comment]
Oh hey. Sorry, I totally missed that.

**Comment by bobthecow** [comment]
Build is failing because this doesn't install on linux. I sent an email to Travis support to request [multi-os support](http://docs.travis-ci.com/user/multi-os/) for this repo so we can install and test.

**Comment by bobthecow** [comment]
Travis has enabled multi-os support for this repo so that we can build it. Right now, it's a bit ugly, because OS X on multi-os doesn't currently support node.js builds (See 08204f5b5d5e08afb8e60916d35549c171a07bf1) … but it does the trick and actually builds now :)

@boennemann @janl Is this fine?

**Comment by janl** [comment]
This is fantastic! <3

**Comment by janl** [comment]
@bobthecow wanna do the merge honours yourself? :)

**Comment by bobthecow** [comment]
Of course!

**Pull request merged**
